### ISSUE TITLE
cant work for nuxt3

### ISSUE THREAD

**Issue by wintsa123** [xxwwp/StorageTiming#1]
!

**Comment by xxwwp** [comment]
Thank you for bringing up the issue. It seems like you're encountering a problem with the StorageTiming library not working in a Nuxt 3 environment. I understand your concern, and you're correct in assuming that the library relies on browser-specific features like localStorage and sessionStorage, which are not available in server-side environments.

Since Nuxt 3 is designed to work both on the client and server side, certain browser-specific functionalities might behave differently or not be available at all when your code runs on the server. To address this issue, you might want to consider modifying your code to conditionally use the StorageTiming library only on the client side, where the browser storage APIs are accessible.

Here's an example of how you could achieve this:

```js
import { onMounted } from 'vue';

export default {
  setup() {
    onMounted(() => {
      // Check if we're on the client side before using StorageTiming
      if (process.client) {
        store.get("key")
        // ...
      }
    });
  },
};
```

This way, you'll ensure that the StorageTiming library is only used when running on the client side, avoiding any issues related to server-side execution.

> !

**Comment by xxwwp** [comment]
> !

StorageTiming cannot be instantiated on the server-side. If you want to use it in Nuxt, you'll need to implement a client-side instantiation solution on your own. For example:

```js
const getStore = (() => {
  let ins;
  return (...args) => {
    if (ins) return ins;
    ins = new Store(...args);
    return ins;
  };
})();
```

Additionally, you won't be able to access StorageTiming's data on the server-side because StorageTiming relies on window.localStorage or window.sessionStorage.

**Comment by wintsa123** [comment]
> > !
> 
> 无法在服务器端实例化存储计时。如果你想在Nuxt中使用它，你需要自己实现一个客户端实例化解决方案。例如：
> 
> ```js
> const getStore = (() => {
>   let ins;
>   return (...args) => {
>     if (ins) return ins;
>     ins = new Store(...args);
>     return ins;
>   };
> })();
> ```
> 
> 此外，您将无法在服务器端访问 StorageTiming 的数据，因为 StorageTiming 依赖于 window.localStorage 或 window.sessionStorage。

ok,i used other function due it.
